name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.14.0', '1.15.0', '1.16.0']

    steps:
      - uses: actions/checkout@v2
    
      - name: set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
    
      - name: deps
        run: |
          make deps-dev

      - name: lint
        run: make lint

      - name: test
        run: make test

      - name: build
        run: make build
